version: "3"
services:
  mytlg_bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${BOT_VOLUME_PATH}:/my_spending_bot/
    env_file: # Указываем явно путь к файлу с переменными окружения
      - .env
    restart: always
    networks:
      - mynetwork
networks:
  mynetwork:
    external: true